spring:
  datasource:
    username: root
    password: root
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${user.dir}/supervisord.db
  jpa:
    database-platform: org.sqlite.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
