spring:
  flyway:
    locations: classpath:/db/migration/mysql
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.21.122:3306/itoa?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
